export { remarkTemplatePlugin } from "./remark/remark-template-plugin";
export { parameterHeadingName, parameterPostfixType } from "./remark/constant";
export type { Platforms, Platform } from "./platform";
export type { Parameter } from "./parameter";
export type { Common } from "./common";
export { validateCommon } from "./common-validate";
export { generateAndroidCommon } from "./android/common";
export { generateWebCommon } from "./web/common";
export type { Event } from "./event";
export { validateEvent } from "./event-validate";
export { generateAndroidEvent } from "./android/event";
export { generateWebEvent } from "./web/event";
